config/routes.rb
Mrtamap::Application.routes.draw do
  get "maps/index"
  get "home/index"
  resources :station_details

  resources :stations

  resources :phase_details

  resources :phases

  mount Ckeditor::Engine => '/ckeditor'
  resources :countries

  resources :line_details

  resources :lines

  root 'home#index'

end

app/models/line.rb
class Line
  include Mongoid::Document
  field :code, type: String
  field :_id, type: String
  has_many :line_details
  has_many :phases
  has_many :stations
  mount_uploader :icon,  IconUploader
  scope :selected, ->(line) {where(:id => line)}

  def getdetails(lang)
    line_details.where(:country => lang)
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  layout 'welcome'
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)
    generate_id
    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line }
      else
        format.html { render action: 'new' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end
  def generate_id
    n = @line.code.downcase.tr(" ","-").tr('"','-').tr('.','-')
    id = "#{n}"
    @line.id = id
  end
  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:code, :icon)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @line.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h4>

      <ul>
      <% @line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :code, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :code, :class => "form-control" %>
    </div>
  </div>
   <div class="form-group">
    <%= f.label :icon, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :icon, :class => "" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/lines/edit.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>

    <div class="page-header">
      <%= link_to lines_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
      <% end %>
      <%= link_to @line, :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-info-sign"></span>
        Show
      <% end %>
      <h1>Editing line</h1>
    </div>

    <%= render 'form' %>

  </div>
</div>

app/views/lines/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
    <div class="page-header">
      <%= link_to new_line_path, :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New Line
      <% end %>
      <h1>Listing lines <i class="icon-remove icon-white "></i> </h1>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover data-table">
        <thead>
          <tr>
            <th>Code</th>
            <th>Icon</th>
            <th> </th>
            <th> </th>
            <th> </th>
          </tr>
        </thead>

        <tbody>
          <%= content_tag_for(:tr, @lines) do |line| %>
            <td><%= line.code %></td>
            <td><%= image_tag line.icon.icon rescue nil %></td>
            <td><%= link_to icon(:"folder-open"), line %></td>
            <td><%= link_to icon(:"pencil"), edit_line_path(line) %></td>
            <td><%= link_to icon(:"trash"), line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/lines/new.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>

    <div class="page-header">
      <%= link_to lines_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
      <% end %>
      <h1>New line</h1>
    </div>

    <%= render 'form' %>

  </div>
</div>

app/views/lines/show.html.erb
<div class="page-header">
  <%= link_to lines_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_line_path(@line), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show line</h1>
</div>

<dl class="dl-horizontal">
  <dt>Code:</dt>
  <dd><%= @line.code %></dd>

</dl>