config/routes.rb
Mrtamap::Application.routes.draw do
  get "maps/index"
  get "home/index"
  resources :station_details

  resources :stations

  resources :phase_details

  resources :phases

  mount Ckeditor::Engine => '/ckeditor'
  resources :countries

  resources :line_details

  resources :lines

  root 'home#index'

end

app/models/station.rb
class Station
  include Mongoid::Document
  field :code, type: String

  field :_id, type: String
  belongs_to :phase
  has_many :station_details
  def getdetails(lang)
    station_details.where(:country => lang)
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  layout 'welcome'
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)
    generate_id
    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render action: 'show', status: :created, location: @station }
      else
        format.html { render action: 'new' }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end
  def generate_id
    p = @station.phase.id
    s = @station.code.downcase.tr(" ","-").tr('"','-').tr('.','-')
    id = "#{p}-#{s}"
    @station.id = id
  end
  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:code, :phase_id)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @station.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h4>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :phase, "รหัสช่วง", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select  :phase_id, Phase.all , :id, :code , {:prompt => "Select Phase "} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :code, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :code, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/stations/edit.html.erb
<div class="page-header">
  <%= link_to stations_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @station, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing station</h1>
</div>

<%= render 'form' %>

app/views/stations/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
<div class="page-header">
  <%= link_to new_station_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Station
  <% end %>
  <h1>Listing stations</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover data-table">
    <thead>
      <tr>
            <th>Phase</th>
            <th>Code</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @stations) do |station| %>
            <td><%= station.phase.code %></td>
            <td><%= station.code %></td>
            <td><%= link_to icon(:"folder-open"), station %></td>
        <td><%= link_to icon(:"pencil"), edit_station_path(station) %></td>
        <td><%= link_to icon(:"trash"), station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/stations/new.html.erb
<div class="page-header">
  <%= link_to stations_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New station</h1>
</div>

<%= render 'form' %>

app/views/stations/show.html.erb
<div class="page-header">
  <%= link_to stations_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_station_path(@station), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show station</h1>
</div>

<dl class="dl-horizontal">
  <dt>Code:</dt>
  <dd><%= @station.code %></dd>

</dl>