config/routes.rb
Mrtamap::Application.routes.draw do
  get "maps/index"
  get "home/index"
  resources :station_details

  resources :stations

  resources :phase_details

  resources :phases

  mount Ckeditor::Engine => '/ckeditor'
  resources :countries

  resources :line_details

  resources :lines

  root 'home#index'

end

app/models/line_detail.rb
class LineDetail
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :_id, type: String

  belongs_to  :line
  belongs_to  :country

  has_many :phases
  scope :lang, ->(lang) {where(:country => lang)}



end

app/controllers/line_details_controller.rb
class LineDetailsController < ApplicationController
  layout 'welcome'
  before_action :set_line_detail, only: [:show, :edit, :update, :destroy]

  # GET /line_details
  # GET /line_details.json
  def index
    @line_details = LineDetail.all
  end

  # GET /line_details/1
  # GET /line_details/1.json
  def show
  end

  # GET /line_details/new
  def new
    @line_detail = LineDetail.new
  end

  # GET /line_details/1/edit
  def edit
  end

  # POST /line_details
  # POST /line_details.json
  def create
    @line_detail = LineDetail.new(line_detail_params)
    generate_id
    respond_to do |format|
      if @line_detail.save
        format.html { redirect_to @line_detail, notice: 'Line detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def generate_id
    n = @line_detail.title.downcase.tr(" ","-").tr('"','-').tr('.','-')
    id = "#{n}"
    @line_detail.id = id
  end
  # PATCH/PUT /line_details/1
  # PATCH/PUT /line_details/1.json
  def update
    respond_to do |format|
      if @line_detail.update(line_detail_params)
        format.html { redirect_to @line_detail, notice: 'Line detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_details/1
  # DELETE /line_details/1.json
  def destroy
    @line_detail.destroy
    respond_to do |format|
      format.html { redirect_to line_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_detail
      @line_detail = LineDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_detail_params
      params.require(:line_detail).permit(:title, :description, :line_id, :country_id)
    end
end

app/helpers/line_details_helper.rb
module LineDetailsHelper
end

app/views/line_details/_form.html.erb
<%= form_for(@line_detail, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @line_detail.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@line_detail.errors.count, "error") %> prohibited this line_detail from being saved:</h4>

      <ul>
      <% @line_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :line, "รหัสโครงการ", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select  :line_id, Line.all , :id, :code , {:prompt => "Select MRTA Line"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :country, "ประเทศ/ภาษา", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select  :country_id, Country.all , :id, :name , {:prompt => "Select Country/Language"} %>
    </div>
  </div>



  <div class="form-group">
    <%= f.label :title, "ชื่อโครงการ", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, "รายละเอียดโครงการ", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/line_details/edit.html.erb
<div class="page-header">
  <%= link_to line_details_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @line_detail, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing line_detail</h1>
</div>

<%= render 'form' %>

app/views/line_details/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
<div class="page-header">
  <%= link_to new_line_detail_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Line detail
  <% end %>
  <h1>Listing line_details</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover data-table">
    <thead>
      <tr>
            <th>Line</th>
            <th>Title</th>
            <th>Description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @line_details) do |line_detail| %>
            <td><%= line_detail.line.code %></td>
            <td><%= line_detail.title %></td>
            <td><%= line_detail.description %></td>
            <td><%= link_to icon(:"folder-open"), line_detail %></td>
        <td><%= link_to icon(:"pencil"), edit_line_detail_path(line_detail) %></td>
        <td><%= link_to icon(:"trash"), line_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/line_details/new.html.erb
<div class="page-header">
  <%= link_to line_details_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h3>รายละเอียดโครงการรถไฟฟ้า</h3>
</div>

<%= render 'form' %>

app/views/line_details/show.html.erb
<div class="page-header">
  <%= link_to line_details_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_line_detail_path(@line_detail), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show line_detail</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @line_detail.title %></dd>

  <dt>Description:</dt>
  <dd><%= @line_detail.description %></dd>

</dl>