config/routes.rb
Mrtamap::Application.routes.draw do
  get "maps/index"
  get "home/index"
  resources :station_details

  resources :stations

  resources :phase_details

  resources :phases

  mount Ckeditor::Engine => '/ckeditor'
  resources :countries

  resources :line_details

  resources :lines

  root 'home#index'

end

app/models/phase_detail.rb
class PhaseDetail
  include Mongoid::Document
  field :no, type: Integer
  field :title, type: String
  field :distance, type: String
  field :status, type: String
  field :description, type: String
  field :_id, type: String

  belongs_to :phase
  belongs_to :country
  scope :lang, ->(lang) {where(:country => lang)}
end

app/controllers/phase_details_controller.rb
class PhaseDetailsController < ApplicationController
  layout 'welcome'
  before_action :set_phase_detail, only: [:show, :edit, :update, :destroy]

  # GET /phase_details
  # GET /phase_details.json
  def index
    @phase_details = PhaseDetail.all
  end

  # GET /phase_details/1
  # GET /phase_details/1.json
  def show
  end

  # GET /phase_details/new
  def new
    @phase_detail = PhaseDetail.new
  end

  # GET /phase_details/1/edit
  def edit
  end

  # POST /phase_details
  # POST /phase_details.json
  def create
    @phase_detail = PhaseDetail.new(phase_detail_params)
    generate_id
    respond_to do |format|
      if @phase_detail.save
        format.html { redirect_to @phase_detail, notice: 'Phase detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phase_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @phase_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def generate_id
    p = @phase_detail.title.downcase.tr(" ","-").tr('"','-').tr('.','-')
    id = "#{p}"
    @phase_detail.id = id
  end
  # PATCH/PUT /phase_details/1
  # PATCH/PUT /phase_details/1.json
  def update
    respond_to do |format|
      if @phase_detail.update(phase_detail_params)
        format.html { redirect_to @phase_detail, notice: 'Phase detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phase_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phase_details/1
  # DELETE /phase_details/1.json
  def destroy
    @phase_detail.destroy
    respond_to do |format|
      format.html { redirect_to phase_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phase_detail
      @phase_detail = PhaseDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phase_detail_params
      params.require(:phase_detail).permit(:no, :title, :distance, :status, :description, :phase_id, :country_id)
    end
end

app/helpers/phase_details_helper.rb
module PhaseDetailsHelper
end

app/views/phase_details/_form.html.erb
<%= form_for(@phase_detail, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @phase_detail.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@phase_detail.errors.count, "error") %> prohibited this phase_detail from being saved:</h4>

      <ul>
      <% @phase_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :phase, "รหัสช่วง", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select  :phase_id, Phase.all , :id, :code , {:prompt => "Select Phase"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :country, "ประเทศ/ภาษา", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select  :country_id, Country.all , :id, :name , {:prompt => "Select Country/Language"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :no, "ระยะ", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :no, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title,"ชื่อช่วง", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :distance, "ระยะทางช่วง", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :distance, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, "สถานะ",:class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :status, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, "รายละเอียด",:class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/phase_details/edit.html.erb
<div class="page-header">
  <%= link_to phase_details_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @phase_detail, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing phase_detail</h1>
</div>

<%= render 'form' %>

app/views/phase_details/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
    <div class="page-header">
      <%= link_to new_phase_detail_path, :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New Phase detail
      <% end %>
      <h1>Listing phase_details</h1>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover data-table">
        <thead>
          <tr>
            <th>No</th>
            <th>Title</th>
            <th>Distance</th>
            <th>Status</th>
            <th>Description</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= content_tag_for(:tr, @phase_details) do |phase_detail| %>
            <td><%= phase_detail.no %></td>
            <td><%= phase_detail.title %></td>
            <td><%= phase_detail.distance %></td>
            <td><%= phase_detail.status %></td>
            <td><%= phase_detail.description %></td>
            <td><%= link_to icon(:"folder-open"), phase_detail %></td>
            <td><%= link_to icon(:"pencil"), edit_phase_detail_path(phase_detail) %></td>
            <td><%= link_to icon(:"trash"), phase_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/phase_details/new.html.erb
<div class="page-header">
  <%= link_to phase_details_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h3>แบ่งช่วงระยะโครงการ</h3>
</div>

<%= render 'form' %>

app/views/phase_details/show.html.erb
<div class="page-header">
  <%= link_to phase_details_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_phase_detail_path(@phase_detail), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show phase_detail</h1>
</div>

<dl class="dl-horizontal">
  <dt>No:</dt>
  <dd><%= @phase_detail.no %></dd>

  <dt>Title:</dt>
  <dd><%= @phase_detail.title %></dd>

  <dt>Distance:</dt>
  <dd><%= @phase_detail.distance %></dd>

  <dt>Status:</dt>
  <dd><%= @phase_detail.status %></dd>

  <dt>Description:</dt>
  <dd><%= @phase_detail.description %></dd>

</dl>